# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('calendar', models.IntegerField(default=0)),
                ('day1', models.IntegerField(default=0)),
                ('month1', models.IntegerField(default=0)),
                ('year1', models.IntegerField(default=0)),
                ('slash1', models.BooleanField(default=False)),
                ('day2', models.IntegerField(blank=True, null=True)),
                ('month2', models.IntegerField(blank=True, null=True)),
                ('year2', models.IntegerField(blank=True, null=True)),
                ('slash2', models.NullBooleanField()),
                ('text', models.CharField(blank=True, max_length=80)),
                ('sortval', models.IntegerField(default=0)),
                ('newyear', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=19, unique=True)),
                ('gramps_id', models.CharField(blank=True, max_length=25, verbose_name=b'ID')),
                ('private', models.BooleanField(verbose_name=b'private')),
                ('public', models.BooleanField(default=True, verbose_name=b'public')),
                ('event_type', models.IntegerField(choices=[(-1, b'Unknown'), (0, b'Custom'), (1, b'Marriage'), (2, b'Marriage Settlement'), (3, b'Marriage License'), (4, b'Marriage Contract'), (5, b'Marriage Banns'), (6, b'Engagement'), (7, b'Divorce'), (8, b'Divorce Filing'), (9, b'Annulment'), (10, b'Alternate Marriage'), (11, b'Adopted'), (12, b'Birth'), (13, b'Death'), (14, b'Adult Christening'), (15, b'Baptism'), (16, b'Bar Mitzvah'), (17, b'Bas Mitzvah'), (18, b'Blessing'), (19, b'Burial'), (20, b'Cause Of Death'), (21, b'Census'), (22, b'Christening'), (23, b'Confirmation'), (24, b'Cremation'), (25, b'Degree'), (26, b'Education'), (27, b'Elected'), (28, b'Emigration'), (29, b'First Communion'), (30, b'Immigration'), (31, b'Graduation'), (32, b'Medical Information'), (33, b'Military Service'), (34, b'Naturalization'), (35, b'Nobility Title'), (36, b'Number of Marriages'), (37, b'Occupation'), (38, b'Ordination'), (39, b'Probate'), (40, b'Property'), (41, b'Religion'), (42, b'Residence'), (43, b'Retirement'), (44, b'Will')], verbose_name=b'EventType')),
                ('description', models.TextField(blank=True, verbose_name=b'description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=19, unique=True)),
                ('gramps_id', models.CharField(blank=True, max_length=25, verbose_name=b'ID')),
                ('private', models.BooleanField(verbose_name=b'private')),
                ('public', models.BooleanField(default=True, verbose_name=b'public')),
                ('family_rel_type', models.IntegerField(choices=[(3, b'Unknown'), (4, b'Custom'), (2, b'Civil Union'), (1, b'Unmarried'), (0, b'Married')], default=3, verbose_name=b'FamilyRelType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(-1, b'Unknown'), (0, b'Custom'), (1, b'Primary'), (2, b'Clergy'), (3, b'Celebrant'), (4, b'Aide'), (5, b'Bride'), (6, b'Groom'), (7, b'Witness'), (8, b'Family'), (9, b'Informant')], default=-1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.Event')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('calendar', models.IntegerField(default=0)),
                ('day1', models.IntegerField(default=0)),
                ('month1', models.IntegerField(default=0)),
                ('year1', models.IntegerField(default=0)),
                ('slash1', models.BooleanField(default=False)),
                ('day2', models.IntegerField(blank=True, null=True)),
                ('month2', models.IntegerField(blank=True, null=True)),
                ('year2', models.IntegerField(blank=True, null=True)),
                ('slash2', models.NullBooleanField()),
                ('text', models.CharField(blank=True, max_length=80)),
                ('sortval', models.IntegerField(default=0)),
                ('newyear', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=19, unique=True)),
                ('gramps_id', models.CharField(blank=True, max_length=25, verbose_name=b'ID')),
                ('private', models.BooleanField(verbose_name=b'private')),
                ('public', models.BooleanField(default=True, verbose_name=b'public')),
                ('path', models.TextField(blank=True)),
                ('mime', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, verbose_name=b'Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyFamilies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=19, unique=True)),
                ('gramps_id', models.CharField(blank=True, max_length=25, verbose_name=b'ID')),
                ('private', models.BooleanField(verbose_name=b'private')),
                ('public', models.BooleanField(default=True, verbose_name=b'public')),
                ('note_type', models.IntegerField(choices=[(-1, b'Unknown'), (0, b'Custom'), (1, b'General'), (2, b'Research'), (3, b'Transcript'), (4, b'Person Note'), (5, b'Attribute Note'), (6, b'Address Note'), (7, b'Association Note'), (8, b'LDS Note'), (9, b'Family Note'), (10, b'Event Note'), (11, b'Event Reference Note'), (12, b'Source Note'), (13, b'Source Reference Note'), (14, b'Place Note'), (15, b'Repository Note'), (16, b'Repository Reference Note'), (17, b'Media Note'), (18, b'Media Reference Note'), (19, b'Child Reference Note'), (20, b'Name Note'), (21, b'Source text'), (22, b'Citation'), (23, b'Report'), (24, b'Html code')], verbose_name=b'NoteType')),
                ('text', models.TextField(blank=True)),
                ('preformatted', models.BooleanField(verbose_name=b'preformatted')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=19, unique=True)),
                ('gramps_id', models.CharField(blank=True, max_length=25, verbose_name=b'ID')),
                ('private', models.BooleanField(verbose_name=b'private')),
                ('public', models.BooleanField(default=True, verbose_name=b'public')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('gender_type', models.IntegerField(choices=[(2, b'Unknown'), (1, b'Male'), (0, b'Female')], default=2, verbose_name=b'GenderType')),
                ('probably_alive', models.BooleanField(verbose_name=b'Probably alive')),
                ('birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='genealogy.Event')),
                ('death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='death', to='genealogy.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(-1, b'Unknown'), (0, b'Custom'), (1, b'Primary'), (2, b'Clergy'), (3, b'Celebrant'), (4, b'Aide'), (5, b'Bride'), (6, b'Groom'), (7, b'Witness'), (8, b'Family'), (9, b'Informant')], default=-1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=19, unique=True)),
                ('gramps_id', models.CharField(blank=True, max_length=25, verbose_name=b'ID')),
                ('private', models.BooleanField(verbose_name=b'private')),
                ('public', models.BooleanField(default=True, verbose_name=b'public')),
                ('title', models.TextField(blank=True)),
                ('long', models.TextField(blank=True)),
                ('lat', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=19, unique=True)),
                ('gramps_id', models.TextField(blank=True, null=True)),
                ('last_saved', models.DateTimeField(auto_now=True, verbose_name=b'last changed')),
                ('last_changed', models.DateTimeField(blank=True, null=True, verbose_name=b'last changed')),
                ('last_changed_by', models.TextField(blank=True, null=True)),
                ('name', models.TextField(verbose_name=b'name')),
                ('color', models.CharField(blank=True, max_length=13, null=True)),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name=b'priority')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(through='genealogy.PersonEvent', to='genealogy.Event'),
        ),
        migrations.AddField(
            model_name='person',
            name='families',
            field=models.ManyToManyField(blank=True, through='genealogy.MyFamilies', to='genealogy.Family'),
        ),
        migrations.AddField(
            model_name='person',
            name='parent_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_family', to='genealogy.Family'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, to='genealogy.Tag'),
        ),
        migrations.AddField(
            model_name='myfamilies',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.Person'),
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, to='genealogy.Tag'),
        ),
        migrations.AddField(
            model_name='family',
            name='events',
            field=models.ManyToManyField(through='genealogy.FamilyEvent', to='genealogy.Event'),
        ),
        migrations.AddField(
            model_name='family',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_ref', to='genealogy.Person'),
        ),
        migrations.AddField(
            model_name='family',
            name='marriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marriage', to='genealogy.Event'),
        ),
        migrations.AddField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_ref', to='genealogy.Person'),
        ),
        migrations.AddField(
            model_name='family',
            name='tags',
            field=models.ManyToManyField(blank=True, to='genealogy.Tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genealogy.Place'),
        ),
    ]
