# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mime',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='long',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='tag',
            name='gramps_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=128, verbose_name=b'name'),
        ),
    ]
