# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='handle',
            field=models.CharField(blank=True, default=None, help_text=b'Uniq handler for remote databases', max_length=32),
        ),
        migrations.AlterField(
            model_name='family',
            name='handle',
            field=models.CharField(blank=True, default=None, help_text=b'Uniq handler for remote databases', max_length=32),
        ),
        migrations.AlterField(
            model_name='media',
            name='handle',
            field=models.CharField(blank=True, default=None, help_text=b'Uniq handler for remote databases', max_length=32),
        ),
        migrations.AlterField(
            model_name='note',
            name='handle',
            field=models.CharField(blank=True, default=None, help_text=b'Uniq handler for remote databases', max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='handle',
            field=models.CharField(blank=True, default=None, help_text=b'Uniq handler for remote databases', max_length=32),
        ),
        migrations.AlterField(
            model_name='place',
            name='handle',
            field=models.CharField(blank=True, default=None, help_text=b'Uniq handler for remote databases', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together=set([('handle', 'tree')]),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set([('handle', 'tree')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('handle', 'tree')]),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('handle', 'tree')]),
        ),
    ]
