# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_auto_20151226_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gramps_id',
        ),
        migrations.RemoveField(
            model_name='family',
            name='gramps_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='gramps_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='gramps_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gramps_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='gramps_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='gramps_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='handle',
            field=models.CharField(blank=True, default=True, help_text=b'Uniq handler for remote databases', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='handle',
            field=models.CharField(blank=True, default=True, help_text=b'Uniq handler for remote databases', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='handle',
            field=models.CharField(blank=True, default=True, help_text=b'Uniq handler for remote databases', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='handle',
            field=models.CharField(blank=True, default=True, help_text=b'Uniq handler for remote databases', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='handle',
            field=models.CharField(blank=True, default=True, help_text=b'Uniq handler for remote databases', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='probably_alive',
            field=models.BooleanField(default=True, verbose_name=b'Probably alive'),
        ),
        migrations.AlterField(
            model_name='place',
            name='handle',
            field=models.CharField(blank=True, default=True, help_text=b'Uniq handler for remote databases', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='handle',
            field=models.CharField(max_length=19, null=True, unique=True),
        ),
    ]
