# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=16)),
                ('description', models.TextField(blank=True)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyTreeImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('file', models.FileField(upload_to=b'trees/')),
                ('type', models.IntegerField(choices=[(0, b'gedcom 5.5')], default=0)),
                ('state', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.FamilyTree')),
            ],
        ),
    ]
